server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈

logging.level:
  org.hibernate.SQL: debug


jwt:
  secret: 928Tt2wf5DZT5yH80ZwReyFEQB3UEIBN+S5mYVUVfh1RgL9M2lFcZn5uXkSrrrOvHhpofrxA1AnTh8X1K3Zr+Q==

kakao:
  client_id: dc7e6161a7c62c424bd5c20892891b30
  redirect_url: http://localhost:3000/oauth/redirected/kakao
  client_secret: KXe6bt4AjeijSW9CkOcoxa5brNbcrH7w

# 업로드 파일 저장 경로
upload:
  path: C:/todo_upload

